### ISSUE TITLE
Project's site goes to a phishing page

### ISSUE THREAD

**Issue by lorenzsandi** [esjeon/pngdefry#1]
The current project's site url now redirects you to some sort of scammy type site unrelated to the PNGDefry project at all. Shouldn't this be updated to at least an archive of the site if one exists?

**Comment by dofuuz** [comment]
Last archive I found:
https://web.archive.org/web/20211120053356/http://www.jongware.com/pngdefry.html Web page
https://web.archive.org/web/20211205021959/http://www.jongware.com/binaries/pngdefry.zip pngdefry v1.2

**Comment by esjeon** [comment]
Thanks for the heads-up. Fixed the README with 5246ef3, and updated the about text too.
